SELECT a.PRODUCT_CODE, SUM(a.PRICE * b.SALES_AMOUNT) as 'SALES'
FROM PRODUCT as a JOIN OFFLINE_SALE as b on a.PRODUCT_ID = b.PRODUCT_ID
GROUP BY a.PRODUCT_CODE
order by SALES desc, a.PRODUCT_CODE asc 
