SELECT a.BOOK_ID, b.AUTHOR_NAME, DATE_FORMAT(a.PUBLISHED_DATE,"%Y-%m-%d") as 'PUBLISHED_DATE'
FROM BOOK as a join AUTHOR as b on a.AUTHOR_ID = b.AUTHOR_ID
where a.CATEGORY = '경제'
order by a.PUBLISHED_DATE 
